version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: newspaper_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: bangladesh_newspaper

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: newspaper_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file: ./backend/.env
    depends_on:
      - mongodb
    volumes:
      - ./backend/app/static/uploads:/app/app/static/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: newspaper_frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
